adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path
from django.conf.urls import url

app_name = 'adminapp'

urlpatterns = [
    url(r'^users/create/$', adminapp.user_create, name='user_create'),
    # url(r'^users/create/$', adminapp.UsersCreateView.as_view(), name='user_create'),
    url(r'^users/read/$', adminapp.UsersListView.as_view(), name='users'),
    url(r'^users/update/(?P<pk>\d+)/$', adminapp.user_update, name='user_update'),
    url(r'^users/delete/(?P<pk>\d+)/$', adminapp.user_delete, name='user_delete'),

    url(r'^categories/create/$', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    url(r'^categories/read/$', adminapp.ProductCategoryListView.as_view(), name='categories'),
    url(r'^categories/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    url(r'^categories/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    url(r'^products/create/category/(?P<pk>\d+)/$', adminapp.ProductCreateView.as_view(), name='product_create'),
    url(r'^products/read/category/(?P<pk>\d+)/$', adminapp.products, name='products'),
    url(r'^products/read/(?P<pk>\d+)/$', adminapp.product_read, name='product_read'),
    url(r'^products/update/(?P<pk>\d+)/$', adminapp.product_update, name='product_update'),
    url(r'^products/delete/(?P<pk>\d+)/$', adminapp.product_delete, name='product_delete'),
    # path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    # path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    # path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    # path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    # path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),





]

authapp/urls.py
from django.conf.urls import url
import authapp.views as views

# app_name = 'authapp'

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^edit/$', views.edit, name='edit'),
    ]

basketapp/urls.py
from django.conf.urls import url

import basketapp.views as basketapp

urlpatterns = [
    url(r'^$', basketapp.basket, name='basket'),
    url(r'^add/(?P<pk>\d+)/$', basketapp.basket_add, name='add'),
    url(r'^remove/(?P<pk>\d+)/$', basketapp.basket_remove, name='remove'),
    url(r'^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basketapp.basket_edit, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from mainApp import views as mainApp
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', mainApp.index, name='mainApp'),
    # url(r'^products/$', mainApp.products, name='products'),
    url(r'^products/', include(('mainApp.urls', 'mainApp'), namespace='products')),
    # url(r'^fishnet_chair/$', mainApp.fishnet_chair, name='fishnet_chair'),

    # url(r'^history/$', mainApp.history, name='history'),
    url(r'^history/$', mainApp.HistoryListView.as_view(), name='history'),

    url(r'^showroom/$', mainApp.showroom, name='showroom'),
    url(r'^contact/$', mainApp.contacts, name='contact'),
    url(r'^auth/', include(('authapp.urls', 'authapp'), namespace='auth')),
    url(r'^basket/', include(('basketapp.urls', 'basketapp'), namespace='basket')),
    url(r'^admin_custom/', include(('adminapp.urls', 'adminapp'), namespace='admin_custom')),
    path('admin/', admin.site.urls),
    url(r'^order/', include(('orderapp.urls', 'orderapp'), namespace='order')),
    # path('admin/', include('adminapp.urls', namespace='admin'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainApp/urls.py
from django.conf.urls import url
from .views import products, product

urlpatterns = [
    url(r'^$', products, name='index'),
    url(r'^(?P<pk>\d+)/$', product, name='product'),
    url(r'^category/(?P<pk>\d+)/$', products, name='category'),
]

orderapp/urls.py
from django.conf.urls import url
import orderapp.views as views

# app_name = 'authapp'

urlpatterns = [
    # url(r'^order/$', views.order, name='login'),
    url(r'^$', views.order, name='order'),
    url(r'^add/$', views.order_add, name='add'),
    # url(r'^add/(?P<pk>\d+)/$', views.order_add, name='add'),
    ]

mainApp/models.py
from django.db import models
from django.contrib.staticfiles.templatetags.staticfiles import static


class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True, default='/products_images/default.png')
    short_desc = models.CharField(verbose_name='харрактеристика кратко', max_length=255, blank=True)
    description = models.TextField(verbose_name='харректеристика подробно', blank=True)
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='склад', default=0)
    category = models.ForeignKey('ProductCategory', on_delete=models.CASCADE, related_name='products')
    trending = models.BooleanField(verbose_name='Тренд', blank=True, default=True)

    def __str__(self):
        return '{}'.format(self.name)

class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    name = models.CharField(verbose_name='имя категории', max_length=64, unique=True)
    description = models.CharField(verbose_name='харрактеристика категории', max_length=256, unique=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name

mainApp/forms.py
from mainApp.models import Product
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

class ShopProductRegisterForm(CreateView):
    class Meta:
        model = Product
        template_name = 'adminapp/products_update.html'
        success_url = reverse_lazy('admin_custom:products')
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ShopProductRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

mainApp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, ProductCategory
from basketapp.models import Basket
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test


def index(request):
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    products = Product.objects.filter(trending=True)
    return render(request, 'mainApp/index.html', locals())


# class ProductsListView(ListView):
#     model = Product
#     template_name = 'adminapp/products.html'
#
#     @method_decorator(user_passes_test(lambda u: u.is_superuser))
#     def dispatch(self, *args, **kwargs):
#         return super().dispatch(*args, **kwargs)


def products(request, pk=None):
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    links_menu = ProductCategory.objects.all()
    category = ProductCategory.objects.all()
    products = Product.objects.all()
    if pk:
        if pk == '0':
            products = Product.objects.all()
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk)
    return render(request, 'mainApp/products.html', locals())


def product(request, pk=None):
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    product = Product.objects.filter(id=int(pk))[0]
    products = Product.objects.filter(category_id=product.category.id)[0:3]
    return render(request, 'mainApp/fishnet_chair.html', locals())

class HistoryListView(ListView):
    model = Basket
    template_name = 'mainApp/history.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            basket = Basket.objects.filter(user=self.request.user)
        return super().dispatch(*args, **kwargs)


    # def history(request):
#     basket = []
#     if request.user.is_authenticated:
#         basket = Basket.objects.filter(user=request.user)
#
#     return render(request, 'mainApp/history.html', locals())

def showroom(request):
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    return render(request, 'mainApp/showroom.html', locals())

def contacts(request):
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    return render(request, 'mainApp/contact.html', locals())

mainApp/templates/mainApp/includes/inc_footer.html
<footer>
    <div class="container">
        <div class="footer-wrap">
            <div class="row flex flex-between">
                <div class="footer-sect has-width-sm">
                    <h5 class="footer-heading">contact us</h5>
                    <p class="footer-text">
                        132A Bridge Road Richmond VIC<br>
                        Australia.
                        <br><br>
                        Talk to us on <a class="in-text-link" href="tel:1300132">1300 132</a><br>
                        <a class="in-text-link" href="mailto:info@interior.com">info@interior.com</a>
                    </p>
                </div>
                <div class="footer-sect">
                    <h5 class="footer-heading">Useful Information</h5>
                    <div class="links-wrap flex flex-between">
                        <div class="link-block">
                            <a href="#" class="footer-link">Sales terms</a>
                            <a href="#" class="footer-link">Customer care</a>
                            <a href="#" class="footer-link">Delivery</a>
                        </div>
                        <div class="link-block">
                            <a href="#" class="footer-link">Architect accounts</a>
                            <a href="#" class="footer-link">Careers</a>
                            <a href="#" class="footer-link">Exchanges & returns</a>
                        </div>
                    </div>
                </div>
                <div class="footer-sect has-width-md">
                    <h5 class="footer-heading">Let’s Stay in Touch!</h5>
                    <p class="footer-text">
                        Suscribe to know about our latest news, products and special offers just for suscribers.
                    </p>
                    <form action="#" method="post">
                        <input type="email" name="email" placeholder="your email address">
                        <button type="submit"><i class="fab fa-telegram-plane"></i></button>
                    </form>
                </div>
            </div>
            <div class="row flex flex-between bottom-footer">
                <p>&copy; Copyright - INTERIOR 2016. All Rights Reserved.</p>
                <div class="socials-block">
                    <a href="#" class="social-icon">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a href="#" class="social-icon">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a href="#" class="social-icon">
                        <i class="fab fa-google-plus-g"></i>
                    </a>
                    <a href="#" class="social-icon">
                        <i class="fab fa-pinterest-p"></i>
                    </a>
                </div>
                <p>Terms & Conditions  /  Privacy policy & Cookies</p>
            </div>
        </div>
    </div>
</footer>

mainApp/templates/mainApp/includes/inc_menu.html
{% load staticfiles %}
<div class="row">
    <header class="flex flex-between">
        <a href="{% url 'mainApp' %}" class="logo">
            <img src="{% static 'img/logo.png' %}" alt="Interior logo">
        </a>
        <nav class="menu">
            <ul class="flex space-between">
                <li><a class="{% if request.resolver_match.url_name == 'mainApp' %}
                        active
                      {% endif %}" href="{% url 'mainApp' %}">HOME</a></li>
                <li><a class="{% if request.resolver_match.url_name == 'index' %}
                        active
                      {% endif %}" href={% url 'products:index' %}>PRODUCTS</a></li>
                <li><a class="{% if request.resolver_match.url_name == 'history' %}
                        active
                      {% endif %}" href={% url 'history' %}>HISTORY</a></li>
                <li><a class="{% if request.resolver_match.url_name == 'showroom' %}
                        active
                      {% endif %}" href={% url 'showroom' %}>SHOWROOM</a></li>
                <li><a class="{% if request.resolver_match.url_name == 'contact' %}
                        active
                      {% endif %}" href="{% url 'contact' %}">CONTACT</a></li>
                <li><a href="#"><i class="fas fa-search"></i></a></li>
            </ul>
        </nav>
    </header>
</div>

mainApp/templates/mainApp/includes/inc_menu_category.html
<div class="products-nav flex flex-between item-center">
    <div class="products-nav">
        <div class="filter-tabs-small flex">
            <a href="{% url 'products:category' 0 %}" class="tab {% if pk == None or pk == '0' %}
                  active
                {% endif %}">All</a>
            {% for foo in links_menu %}
                <a href="{% url 'products:category' foo.pk %}" class="tab {% if request.resolver_match.kwargs.pk|add:'0' == foo.pk %}
                  active
                {% endif %}">{{ foo.name }} </a>
            {% endfor %}
        </div>
    </div>
</div>

mainApp/templates/mainApp/includes/inc_navbar.html
<nav>
  <div class="container flex-container">
      <div>
          {% if user.is_anonymous %}
              <h3>Ты кто?</h3>
              <div>
                  Выполни <a href="{% url 'auth:login' %}"> вход </a> или <a href="{% url 'auth:register' %}">зарегистрируйся</a>
              </div>
          {% else %}
              <a href="{% url 'auth:edit' %}">Привет, {{ user.username|title }}!</a>
                {% if user.is_superuser %}
                <li>
                  <a href="{% url 'admin_custom:users' %}">админка</a>
                </li>
                {% endif %}
              <a href="{% url 'auth:logout' %}">Выход</a>

          {% endif %}
      </div>

    <form>
        <a href="{% url 'basket:basket' %}">Корзина
            <span>
            {% if basket %} {{ basket.0.total_quantity }} {% endif %}
            </span>
        </a>
    </form>
  </div>
</nav>

mainApp/templates/mainApp/includes/inc_products.html
{% load staticfiles %}
<div class="products-grid flex flex-between">
    {% for product in products %}
        <div class="product">
            {% if product.image %}
                <img class="img-responsive" src={{ product.image.url }} alt="" >
            {% endif %}
            <div class="hover-overlay flex">
                <a href="{% url 'products:product' product.id %}" class="primary-btn">
                    <i class="fa fa-chevron-right"></i>
                </a>
                <h2 class="product-name">
                    {{ product.name }}
                </h2>
                <p class="product-desc">{{ product.short_desc }}</p>
                <a href="{% url 'basket:add' product.pk %}" class="basket-btn">Добавить в корзину</a>
            </div>
        </div>
    {% endfor %}
</div>