authapp/urls.py
from django.conf.urls import url
import authapp.views as views

# app_name = 'authapp'

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^edit/$', views.edit, name='edit'),
    ]

basketapp/urls.py
from django.conf.urls import url

import basketapp.views as basketapp

urlpatterns = [
    url(r'^$', basketapp.basket, name='basket'),
    url(r'^add/(?P<pk>\d+)/$', basketapp.basket_add, name='add'),
    url(r'^remove/(?P<pk>\d+)/$', basketapp.basket_remove, name='remove'),
    url(r'^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basketapp.basket_edit, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from mainApp import views as mainApp
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', mainApp.index, name='mainApp'),
    # url(r'^products/$', mainApp.products, name='products'),
    url(r'^products/', include(('mainApp.urls', 'mainApp'), namespace='products')),
    # url(r'^fishnet_chair/$', mainApp.fishnet_chair, name='fishnet_chair'),

    # url(r'^history/$', mainApp.history, name='history'),
    url(r'^history/$', mainApp.HistoryListView.as_view(), name='history'),

    url(r'^showroom/$', mainApp.showroom, name='showroom'),
    url(r'^contact/$', mainApp.contacts, name='contact'),
    url(r'^auth/', include(('authapp.urls', 'authapp'), namespace='auth')),
    url(r'^basket/', include(('basketapp.urls', 'basketapp'), namespace='basket')),
    url(r'^admin_custom/', include(('adminapp.urls', 'adminapp'), namespace='admin_custom')),
    path('admin/', admin.site.urls),
    url(r'^order/', include(('orderapp.urls', 'orderapp'), namespace='order')),
    # path('admin/', include('adminapp.urls', namespace='admin'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainApp/urls.py
from django.conf.urls import url
from .views import products, product

urlpatterns = [
    url(r'^$', products, name='index'),
    url(r'^(?P<pk>\d+)/$', product, name='product'),
    url(r'^category/(?P<pk>\d+)/$', products, name='category'),
]

orderapp/urls.py
from django.conf.urls import url
import orderapp.views as views

# app_name = 'authapp'

urlpatterns = [
    # url(r'^order/$', views.order, name='login'),
    url(r'^$', views.order, name='order'),
    url(r'^add/$', views.order_add, name='add'),
    # url(r'^add/(?P<pk>\d+)/$', views.order_add, name='add'),
    ]

basketapp/models.py
from django.db import models
from django.conf import settings
from mainApp.models import Product


class Basket(models.Model):
    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='Количество', default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created = models.DateTimeField(verbose_name='время добавления', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='время последнего изменения', auto_now=True)

    def save(self, *args, **kwargs):
        self.total_price = int(self.product.price) * self.quantity
        super(Basket, self).save(*args, **kwargs)

    def _get_product_cost(self):
        return self.product.price * self.quantity

    product_cost = property(_get_product_cost)

    def _get_total_quantity(self):
        _items = Basket.objects.filter(user=self.user)
        _totalquantity = sum(list(map(lambda x: x.quantity, _items)))
        return _totalquantity

    total_quantity = property(_get_total_quantity)

    def _get_total_cost(self,id=None):
        _items = Basket.objects.filter(user=self.user)
        _totalcost = sum(list(map(lambda x: x.product_cost, _items)))
        return _totalcost

    total_cost = property(_get_total_cost)

basketapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, reverse
from basketapp.models import Basket
from mainApp.models import Product
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.template.loader import render_to_string

@login_required
def basket(request):
    basket = Basket.objects.filter(user=request.user)
    return render(request, 'basketapp/basket.html', locals())

@login_required
def basket_add(request, pk):
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('products:product', args=[pk]))

    product = get_object_or_404(Product, pk=pk)
    old_basket_item = Basket.objects.filter(user=request.user, product=product)

    if old_basket_item:
        old_basket_item[0].quantity += 1
        old_basket_item[0].save()
    else:
        new_basket_item = Basket(user=request.user, product=product)
        new_basket_item.quantity += 1
        new_basket_item.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)
    basket_record.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def basket_edit(request, pk, quantity):
    if request.is_ajax():
        quantity = int(quantity)
        new_basket_item = Basket.objects.get(pk=int(pk))

        if quantity > 0:
            new_basket_item.quantity = quantity
            new_basket_item.save()
        else:
            new_basket_item.delete()

        basket = Basket.objects.filter(user=request.user). \
            order_by('product__category')
        result = render_to_string('basketapp/includes/inc_basket_list.html', locals())

        return JsonResponse({'result': result})

basketapp/templates/basketapp/includes/inc_basket_list.html
<div class="container basket_list">
    <div class="row">
    {% if basket %}
         <div class="col-lg-8 col-lg-offset-2">
             <h3 class="text-center">Товары в корзине</h3>
              <form class="form-horizontal" method="post">{% csrf_token %}
                <table class="table text-center">
                    <thead>
                            <tr>
                                <th>Название товара</th>
                                <th>Количество</th>
                                <th>Цена за еденицу</th>
                                <th>Общая цена</th>
                            </tr>
                        </thead>
                    <tbody>
                        {% for foo in basket %}
                            <tr>
                                <td>
                                    <a href="{% url 'products:product' foo.product.id %}">{{ foo.product.name }}</a>
                                </td>
                                <td>
                                    <input value="{{ foo.quantity }}" type="number" name="{{ foo.pk }}"
                                           min="0">
                                </td>
                                <td>
                                    <span>
                                        {{ foo.product.price }}
                                    </span>
                                </td>
                                <td>
                                    <span>
                                        {{ foo.total_price }}
                                    </span>
                                </td>
                                <td>
                                    <a href="{% url 'basket:remove' foo.id %}">X</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
              <h5>Общая стоимость </h5>
                <div>
                    <b>Сумма заказа: </b><span id="total_order_amount">{{ basket.0.total_cost }}</span>
                </div>
                <div>
{#                    <button type="submit">Заказать</button>#}
{#                    {% url 'basket:add' product.pk %}#}
{#                    {% url 'ordder:add' basket.id %}#}
                    <a href="{% url 'order:order' %}" >Заказать</a>
                </div>
            </form>
        </div>
    {% else %}
            <h3 class="text-center">В вашей корзине нет заказа</h3>
    {% endif %}
    </div>
</div>