adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path
from django.conf.urls import url

app_name = 'adminapp'

urlpatterns = [
    url(r'^users/create/$', adminapp.user_create, name='user_create'),
    # url(r'^users/create/$', adminapp.UsersCreateView.as_view(), name='user_create'),
    url(r'^users/read/$', adminapp.UsersListView.as_view(), name='users'),
    url(r'^users/update/(?P<pk>\d+)/$', adminapp.user_update, name='user_update'),
    url(r'^users/delete/(?P<pk>\d+)/$', adminapp.user_delete, name='user_delete'),

    url(r'^categories/create/$', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    url(r'^categories/read/$', adminapp.ProductCategoryListView.as_view(), name='categories'),
    url(r'^categories/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    url(r'^categories/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    url(r'^products/create/category/(?P<pk>\d+)/$', adminapp.ProductCreateView.as_view(), name='product_create'),
    url(r'^products/read/category/(?P<pk>\d+)/$', adminapp.products, name='products'),
    url(r'^products/read/(?P<pk>\d+)/$', adminapp.product_read, name='product_read'),
    url(r'^products/update/(?P<pk>\d+)/$', adminapp.product_update, name='product_update'),
    url(r'^products/delete/(?P<pk>\d+)/$', adminapp.product_delete, name='product_delete'),
    # path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    # path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    # path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    # path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    # path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),





]

authapp/urls.py
from django.conf.urls import url
import authapp.views as views

# app_name = 'authapp'

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^edit/$', views.edit, name='edit'),
    ]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from mainApp import views as mainApp
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', mainApp.index, name='mainApp'),
    # url(r'^products/$', mainApp.products, name='products'),
    url(r'^products/', include(('mainApp.urls', 'mainApp'), namespace='products')),
    # url(r'^fishnet_chair/$', mainApp.fishnet_chair, name='fishnet_chair'),

    # url(r'^history/$', mainApp.history, name='history'),
    url(r'^history/$', mainApp.HistoryListView.as_view(), name='history'),

    url(r'^showroom/$', mainApp.showroom, name='showroom'),
    url(r'^contact/$', mainApp.contacts, name='contact'),
    url(r'^auth/', include(('authapp.urls', 'authapp'), namespace='auth')),
    url(r'^basket/', include(('basketapp.urls', 'basketapp'), namespace='basket')),
    url(r'^admin_custom/', include(('adminapp.urls', 'adminapp'), namespace='admin_custom')),
    path('admin/', admin.site.urls),
    url(r'^order/', include(('orderapp.urls', 'orderapp'), namespace='order')),
    # path('admin/', include('adminapp.urls', namespace='admin'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainApp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from authapp.models import ShopUser
from django.shortcuts import get_object_or_404, render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from mainApp.models import Product, ProductCategory
from mainApp.forms import ShopProductRegisterForm
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from authapp.forms import ShopUserRegisterForm
from adminapp.forms import ShopUserAdminEditForm, ProductEditForm
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from django import forms

# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     title = 'админка/пользователи'
#
#     users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#
#     content = {
#         'title': title,
#         'object_list': users_list
#     }
#
#     return render(request, 'adminapp/users.html', content)
#
class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# class UsersCreateView(CreateView):
#     model = ShopUser
#     template_name = 'adminapp/user_update.html'
#     success_url = reverse_lazy('admin_custom:user_update')
#     # fields = '__all__'
#     fields = ('username', 'first_name', 'email', 'password', 'age', 'avatar')
#
#     @method_decorator(user_passes_test(lambda u: u.is_superuser))
#     def dispatch(self, *args, **kwargs):
#         if self.request.method == 'POST':
#             if int(self.request.POST['age']) < 18:
#                 raise forms.ValidationError("Вы слишком молоды!")
#             # self.model.objects.create()
#         return super(UsersCreateView, self).dispatch(*args, **kwargs)

@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = 'пользователи/создание'

    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin_custom:users'))
    else:
        user_form = ShopUserRegisterForm()

    content = {'title': title, 'form': user_form}

    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = 'пользователи/редактирование'

    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES,instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin_custom:user_update', args=[edit_user.pk]))
    else:
        edit_form = ShopUserAdminEditForm(instance=edit_user)

    content = {'title': title, 'update_form': edit_form}

    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = 'пользователи/удаление'

    user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        # user.delete()
        # вместо удаления лучше сделаем неактивным
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('admin_custom:users'))

    content = {'title': title, 'user_to_delete': user}

    return render(request, 'adminapp/user_delete.html', content)


class ProductCategoryListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(ProductCategoryListView, self).dispatch(*args, **kwargs)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/categories_update.html'
    success_url = reverse_lazy('admin_custom:categories')
    fields = '__all__'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(ProductCategoryCreateView, self).dispatch(*args, **kwargs)


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/categories_update.html'
    success_url = reverse_lazy('admin_custom:categories')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(ProductCategoryUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'
        return context


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/categories_update.html'
    success_url = reverse_lazy('admin_custom:categories')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = 'админка/продукт'

    category = get_object_or_404(ProductCategory, pk=pk)
    products_list = Product.objects.filter(category__pk=pk).order_by('name')

    content = {
        'title': title,
        'category': category,
        'objects': products_list,
    }

    return render(request, 'adminapp/products.html', content)


# @user_passes_test(lambda u: u.is_superuser)
# def product_create(request, pk):
#     title = 'товары/создание'
#
#     if request.method == 'POST':
#         user_form = ShopProductRegisterForm(request.POST, request.FILES)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin_custom:products'))
#     else:
#         user_form = ShopProductRegisterForm()
#
#     content = {'title': title, 'update_form': user_form}
#
#     return render(request, 'adminapp/products_update.html', content)

class ProductCreateView(CreateView):
    model = Product
    template_name = 'adminapp/products_update.html'
    success_url = reverse_lazy('admin_custom:products')
    fields = '__all__'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(ProductCreateView, self).dispatch(*args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def product_read(request, pk):
    pass


@user_passes_test(lambda u: u.is_superuser)
def product_update(request, pk):
    title = 'товары/редактирование'

    edit_user = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin_custom:product_update', args=[edit_user.pk]))
    else:
        edit_form = ProductEditForm(instance=edit_user)

    content = {'title': title, 'update_form': edit_form}

    return render(request, 'adminapp/products_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def product_delete(request, pk):
    title = 'товар/удаление'

    product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        # user.delete()
        # вместо удаления лучше сделаем неактивным
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse('admin_custom:products'))

    content = {'title': title, 'update_form': product}

    return render(request, 'adminapp/products_update.html', content)

adminapp/templates/adminapp/base.html
<body>
  <div class="admin_container">
    <div class="h2 text-center head">
      Админка
    </div>
    {% block menu %}
      <div class="admin_menu">
        {% include 'adminapp/includes/inc_menu.html' %}
      </div>
    {% endblock %}
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="categories_list">
    <button class="new_category">
      <a href={% url 'admin_custom:category_create' %}>
        Создать новую категорию
      </a>
    </button>

    {% for object in object_list %}
      <div class="category_record">
        <div class="category_name">
          {{ object.name|title }}
        </div>
        <div class="category_actions">
          <button>
            <a href={% url 'admin_custom:products' object.pk %}>
              товары категории
            </a>
          </button>
          <button>
            <a href={% url 'admin_custom:category_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin_custom:category_delete' object.pk %}>
              удалить
            </a>
          </button>
        </div>
        <div class="category_desc">
          {{ object.description|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

adminapp/templates/adminapp/categories_update.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin_custom:categories' %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="products_list">
    <button class="new_product">
      <a href={% url 'admin_custom:product_create' category.pk %}>
        новый продукт
      </a>
    </button>
		
    {% for object in objects %}
      <div class="product_record">
        <img 
          src="/media/{{object.image|default:'products_images/default.jpg'}}"
          alt="{{ object.name }}">
        <div class="product_name">
          {{ object.name|title }}
        </div>
        <div class="product_actions">
{#          <button>#}
{#            <a href={% url 'admin_custom:product_read' object.pk %}>#}
{#              подробнее#}
{#            </a>#}
{#          </button>#}
          <button>
            <a href={% url 'admin_custom:product_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin_custom:product_delete' object.pk %}>
              удалить
            </a>
          </button>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ object.price }} руб</p>
          <b>количество</b>
          <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ object.short_desc|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

adminapp/templates/adminapp/products_update.html
{#{% extends 'authapp/base.html' %}#}
{% load staticfiles %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin_custom:categories' %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ user_to_delete.username }} 
    {% if user_to_delete.first_name %} {{ user_to_delete.first_name|title }} </b>
      {% if user_to_delete.last_name %}
        {{ user_to_delete.last_name|title }}
      {% endif %})
    {% endif %}
    ?
    <form action="{% url 'admin_custom:user_delete' user_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin_custom:users' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
{#    {{ update_form.as_p }}#}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin_custom:users' %}">
      к списку пользователей
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="users_list">
    <button class="new_user">
      <a href={% url 'admin_custom:user_create' %}>
        новый пользователь
      </a>
    </button>
    {% for object in object_list %}
      <div 
       class="user_record {% if not object.is_active %}not_active{% endif %}">
        <img 
          src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}"
          alt="{{ object.username }}">
        <div class="user_role">
          {% if object.is_superuser %}
            администратор
          {% else %}
            пользователь
          {% endif %}
          <button>
            <a href={% url 'admin_custom:user_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin_custom:user_delete' object.pk %}>
              удалить
            </a>
          </button>
        </div>
        <div class="user_name">
          <p><strong>{{ object.username }}</strong></p>
	    <p>
            {% if object.first_name %}
              <b>{{ object.first_name|title }}</b>
                {% if object.last_name %}
                  <p>{{ object.last_name|title }}</p>
                {% endif %}
            {% endif %}
          </p>
        </div>
        <div class="user_age">
          age:<br>
          {{ object.age }} лет
        </div>
        <div class="user_email">
          email:<br>
          {{ object.email }}
        </div>
        <div class="user_lastlogin">
          logged:<br>
          {{ object.last_login }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}